INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('9 Meters Biopharma', '3');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('7C Solarparken AG', '4');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('8000 Inc', '4');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('808 Renewable Energy Corporation', '4');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('88 Energy ', '4');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('89bio', '4');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('8x8', '4');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('5N Plus ', '5');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('5th Planet Games A/S', '5');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('908 Devices ', '5');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('9342-8530 Québec ', '5');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('99 Acquisition Group ', '5');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('01 Communique Laboratory ', '6');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('420 Property Management', '6');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('5G Networks ', '6');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('60 Degrees Pharmaceuticals', '6');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('60 Degrees Pharmaceuticals - Equity Warrant', '6');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('79North ', '6');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('99 Acquisition Group  - Equity Right', '6');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('99 Acquisition Group  - Equity Warrant', '6');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('9F  - Depositary Receipt (Common Stock)', '6');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('A O Smith Corporation', '6');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('A SPAC II Acquisition Corp', '6');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('A SPAC II Acquisition Corp - Equity Right', '6');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('A SPAC II Acquisition Corp - Equity Warrant', '6');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('A&W Revenue Royalties Income Fund', '6');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('A-Mark Precious Metals', '6');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('A-Sonic Aerospace ', '6');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('29Metals ', '7');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('3SBio ', '7');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('49 North Resources ', '7');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('4Cable TV International', '7');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('4Front Ventures Corp', '7');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('4imprint Group plc', '7');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('51Talk Online Education Group - Depositary Receipt (Common Stock)', '7');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('5:01 Acquisition Corp', '7');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('5E Advanced Materials', '7');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('727 Communications', '7');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('YanGuFang International Group ', '7');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('Yankuang Energy Group Company  - Depositary Receipt (Common Stock)', '7');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('0187279 BC ', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1-800-FLOWERSCOM', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('10X Capital Venture Acquisition Corp III', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('10X Capital Venture Acquisition Corp III - Equity Warrant', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1ST SUMMIT BANCORP of Johnstown', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1st Capital Bancorp', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1st Colonial Bancorp', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1st Federal Savings Bank of SC', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1st NRG Corp', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1st Source Corporation', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1stdibsCom', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('2020 Bulkers ', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('21Shares AG - Amun Ripple (xrp) ETN', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('23andMe Holding ', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('286 Lenox Partners LLC', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('2U', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('3 Sixty Risk Solutions ', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('3M Company', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('3Power Energy ', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('3iQ Bitcoin ETF', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('4D Molecular Therapeutics', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('4D pharma plc - Equity Warrant', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('4DMedical ', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('4DS Memory ', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('Yangtze River Port and Logistics ', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('Yangzijiang Financial Holding ', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('Yangzijiang Shipbuilding (Holdings) ', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('Yankuang Energy Group Company ', '8');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('10x Genomics', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('111 - Depositary Receipt (Common Stock)', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1399 Internet Technology Application Group ', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('141 Capital', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('17 Education & Technology Group  - Depositary Receipt (Common Stock)', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('180 Degree Capital Corp', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('180 Life Sciences Corp', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('180 Life Sciences Corp - Equity Warrant', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1812 Brewing Company ', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1847 Holdings LLC', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1867 Western Financial Corporation', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1895 Bancorp of Wisconsin', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1911 Gold Corporation', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1933 Industries ', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1CM ', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1PM Industries', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1mage Software', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('22nd Century ', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('24SevenOffice Group AB (publ)', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('2seventy bio', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('361 Degrees International ', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('36Kr Holdings  - Depositary Receipt (Common Stock)', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('37 Capital ', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('374Water ', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('3D Pioneer Systems ', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('3D Systems Corporation', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('3DShoppingcom', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('3DX Industries', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('3i Group plc', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('3i Group plc - Depositary Receipt (Common Stock)', '9');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1511419 Ontario ', '10');
INSERT OR IGNORE INTO TrainedEmployees (ProjectName, NumberOfTrainedEmployees) VALUES ('1606 Corp', '10');
